### ISSUE TITLE
WPS proposal is showing wrong Dates

### ISSUE THREAD

**Issue by ackza** [Telos-Foundation/Sqrl#143]
![image](https://user-images.githubusercontent.com/33010254/65685185-4602c600-e016-11e9-90b2-fd62170d35b9.png)

>Weekly telos Posts on Steem: Utilizing Steempeak and Likwid to use same 2500 Telos to get on front page of steem every week. (#33)
Proposed By ackzaontelos
Start BallotCancel Proposal
Cycle: 0 of 1

Here is the error
>Voting Begins: Sun Feb 10 2047 21:46:07 GMT-0800
Voting Ends: Mon Mar 11 2047 21:12:47 GMT-0700

Roger from EOS Uk TELOS UK said he replicated the issue on the test net "so we will need to ask Marlon and TeamSqrl to have a look at that if they are not already aware"

Thanks!

**Comment by ackza** [comment]
Thanks to @dapperd @goodblocks for telling me on official telos telegram that i can just click start and the dates will correct themselves, maybe we can hide them for now until` Telos end when they show up correctly? We shouldn't even show teh incorrect dates i bet they werent even suposed to be there in first places
![image](https://user-images.githubusercontent.com/33010254/65702630-3300ed80-e038-11e9-9dbd-29714371a48f.png)

ANYWAy the FIX is to ignore this and just click START BALLOT But id still enjoy seeing this get fixed properly ;) Maybe just hiding the datyes untill they show up at tehe nd would work just fine. Thanks again and i LOVE The way telos is working out! I couldn't ask for a better Blockchain/

**Comment by marlonwilliams** [comment]
Thanks! We’ll consider incorporating your feedback in the next release. 👍
