### ISSUE TITLE
Simple Request: Add the word "telos" to SQRL Wallet so its SQRL Telos Wallet to remind users

### ISSUE THREAD

**Issue by ackza** [Telos-Foundation/Sqrl#144]
can SQRL wallet next version change its name to SQRL Telos Wallet so people who have it installed remember what it is for? 

When i search telos on windows nothin comes up, sqrl should come up, and many new users may forget what SQRL is even for. I feel we should not leave out the name TELOS even though SQRL is for more than telos, I feel it is a telos desktop wallet and should have the name TELOS WALLET in it just like Greymass is also called EOS VOTER 

if we DONT add the word telos, a large portion of people will not know its a telos wallet. We sometimes forget how much the rest of the world doesn't know about what we do. We should assume no one knows what SQRL is so changing the name to SQRL Telos Wallet or SQRL (Telos Desktop Wallet) or something will just be so much easier to explain for new users.

**Comment by marlonwilliams** [comment]
We would like to keep it just as Sqrl. The website and any other areas indicate it’s focus on Telos and that’s sufficient 😉
