### ISSUE TITLE
Request: Add proposal Amounts, to avoid clicking each proposal to see how big it is(and allow sorting by Amount)

### ISSUE THREAD

**Issue by ackza** [Telos-Foundation/Sqrl#145]
First of all Thank you so much for a great proposal system and A+ SQRL Wallet I love it but wish I could see the proposals request amounts I would like to request that we can see the proposal amounts on the titles, without clicking on each one. 

if I could see how much each proposal is asking for without having to click on them i could more likely vote a lot faster and people would engage easier. 

can we also have the proposal sorted by amount of telos requested?

**Comment by marlonwilliams** [comment]
Added in 1.2.0
