### ISSUE TITLE
Allow TLOS REX to be calculated in TLOS (Just like Ram is also calculated in TLOS) 

### ISSUE THREAD

**Issue by ackza** [Telos-Foundation/Sqrl#146]
We need to show the TLOS REX in TLOS not just rex, and in teh same way we show TLOS RAM in TLOS and in RAM 

![image](https://user-images.githubusercontent.com/33010254/68521299-90ea3d00-0254-11ea-8a6a-30e15e7a92c4.png)

Thank you and youre doing a great job aon SQRL Telos foundation Jesta Marlon and SQRL wallet team! I know youll have these features that surpass greymass and we can see more buttons and abilities to see prices of rex, times it will take to get as much as we need, and schedules and charts showing us our investment value over time.  I want that in the baclkkground as an aque image of just the telpos price slowly goin gup LD

**Comment by marlonwilliams** [comment]
This has been added to v1.2.0
