### ISSUE TITLE
Feature request: Show the total percentage of the WPS reward pool each proposal is asking for. 

### ISSUE THREAD

**Issue by ackza** [Telos-Foundation/Sqrl#155]
Suggestion for adding Pie charts to every proposal, showing how much percent of the total reward pool every proposal is asking for, with even grouping and results at the top showing peoples TOTAL requests, so people would see 'Ackza has 10 proposals but all of his proposals combined is still asking in total less than anyone else. 

So a 100,000 Telos Proposal would take up 10% of the 1 million a month telos and show on the pie chart as taking up a whole 10% visually, and that will let people see with clarity whats going on... with multiple pie charts 

Anyway thanks marlon ! the BRANO , master of Squirrels!

**Comment by marlonwilliams** [comment]
This was added to v1.2.0 in the summary section
