### ISSUE TITLE
The Wallet is out of response after passord saved.

### ISSUE THREAD

**Issue by cs2world** [Telos-Foundation/Sqrl#160]
I have tried the sql1.1.0
Thanks a lot for letting create a free account on Telos blockchain.
Then I saved it with a password.
Then it shows like this:
![image](https://user-images.githubusercontent.com/35934096/69024546-1322e180-0978-11ea-9c95-2773d573163c.png)
Then try to open and reload
Nothing happened.

Thanks.

**Comment by marlonwilliams** [comment]
Closing and reopening works. However, we recommend downloading the latest version where this was resolved altogether.
