### ISSUE TITLE
New account opening error

### ISSUE THREAD

**Issue by Majutsu** [Telos-Foundation/Sqrl#18]
Cannot open new account.  SQRL window goes to grey when 1st letter of account name is entered
![picture1](https://user-images.githubusercontent.com/44127761/46911780-8a798b00-cf98-11e8-8654-58a756b61a93.png)
![picture2](https://user-images.githubusercontent.com/44127761/46911781-8ea5a880-cf98-11e8-81cb-1671c4d851ed.png)

**Comment by Majutsu** [comment]
my error

**Comment by Balaguru-nallusamy** [comment]
I am not able to create new account and the error was not clear. please find the screenshot
