### ISSUE TITLE
Sqrl 0.5.3 wrong token math (UI bug)

### ISSUE THREAD

**Issue by fcecin** [Telos-Foundation/Sqrl#30]
My account in the testnet is ge2damjqgage and my Sqrl 0.5.3 (appImage release on Ubuntu 18.04) shows the following in the wallet Balances tab:

=======================================

Liquid | 0.0505 TLOS
-- | --
Staked to Self | 12000.0000 TLOS
Staked to Others | 557.2264 TLOS
Unstaking | 557.2264 TLOS (3 days from now)
Total | 13114.5033 TLOS
RAM Amount | 100 kB

=======================================

I have a total of 12557.2264 TLOS, not 13114.5033. What it is showing is the result immediately after I have unstaked exactly 557.2264 TLOS, leaving 12000 staked. But the UI duplicates my Unstaking balance as "Staked to Others", which is false, and that's how it gets the 13114.5033 total figure, which is wrong.

( Interestingly, the official block explorer suffers from the inverse problem, and doesn't report my unstaking balance at all, telling me I have 12000 TLOS total. http://testnet.telosfoundation.io/account/ge2damjqgage )

**Comment by fcecin** [comment]
UPDATE: I just tabbed away within the wallet to "Governance" and back into the "Wallet" tab, and the "Staked to Others" amount disappeared.

**Comment by marlonwilliams** [comment]
Yes, this updates on the next refresh. Thanks for reporting it!
