### ISSUE TITLE
Installation issue, No such file or directory: 'install'

### ISSUE THREAD

**Issue by Kinzowa** [Telos-Foundation/Sqrl#31]
Hello,

As others users I'm facing an error with `yarn` when running the installation of Telos on Ubuntu 18.04 : 
```
user@ideapad-710s-13isk:~/telos/Sqrl$ yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

```
Any idea how to sort it out?

**Comment by marlonwilliams** [comment]
make sure you have yarn installed as well as npm and try again.
