### ISSUE TITLE
SQRL 0.5.4 for MAC dmg have some issue in the manage wallet

### ISSUE THREAD

**Issue by eosimpera** [Telos-Foundation/Sqrl#45]
The last release of Sqrl 0.5.4 have the issue when you go to manage wallet it become stuck.

**Comment by marlonwilliams** [comment]
this issue has been tested cannot be reproduced. please download the latest binaries and try again

**Comment by educatedwarrior** [comment]
I have the same issue.

![image](https://user-images.githubusercontent.com/4054610/50289933-35df0a00-0438-11e9-8338-5a18df7b4646.png)

**Comment by kchan725** [comment]
I have same issue, Manage Wallet returns blank. I'm running  version 0.5.4 on Mac. Please kindly fix it soon.
