### ISSUE TITLE
Tools > Manage Wallets goes to blank screen in 0.5.4

### ISSUE THREAD

**Issue by educatedwarrior** [Telos-Foundation/Sqrl#47]
Please take a look at this issue.  Can do manage wallet on Windows version.  I can recreate the issue through screenshare if you like.

Similar Issue was closed - #45

**Comment by ninjaatnight** [comment]
I had same issue on Mac, and managed to get it to work somehow.  Here is what I did, I go to Tools -> Reset Application, delete existing account. then relaunch it and select Telos Mainnet on first screen. After that, Manage Wallets starts working and able to add multiple wallets. Hope this helps.

**Comment by educatedwarrior** [comment]
If you have to do all that , then this is an issue.  I imported the account into EOS Voter and didn't have any issues.

**Comment by marlonwilliams** [comment]
Please download the latest 0.5.5 version, then go to Tools->Advanced->Reset and try again. That's the fix for now...or you can always just use EOS Voter if this breaks your heart.

**Comment by educatedwarrior** [comment]
Doesn't break my heart at all @marlonwilliams .   I wish I knew as half as you do about development.  Great work on SQRL.   I'll continue to report any bugs if I see any ... I hope I can be helpful in that way.   Thanks.
