### ISSUE TITLE
Transfer fails -"Transaction should have at least one required authority"

### ISSUE THREAD

**Issue by bitcoiners** [Telos-Foundation/Sqrl#48]
Tried transfering TLOS and failed with:
![image](https://user-images.githubusercontent.com/38520/50321596-2cbb6f00-0504-11e9-92af-05dabe2ee6b4.png)

**Comment by marlonwilliams** [comment]
Please download the latest 0.5.5 version, then go to Tools->Advanced->Reset and try again.
