### ISSUE TITLE
SQRL CRASH: Setup of 0.5.5 SQRL on Windows - DELETE CUSTOM BLOCKCHAIN NETWORK  

### ISSUE THREAD

**Issue by HologramX** [Telos-Foundation/Sqrl#50]
Setup of 0.5.5 SQRL on Windows DELETE CUSTOM BLOCKCHAIN NETWORK  so must set a  wallet on supported BC BEFORE INSTALL OR SQRL COMPLETELY CRASH!!!

**Comment by HologramX** [comment]
I was unable to change wallet or change account .. finally  I need to RESET Application.

**Comment by marlonwilliams** [comment]
Yes, the workaround after upgrading is to go to Tools -> Advanced Tools -> Reset.
