### ISSUE TITLE
Failed transacton

### ISSUE THREAD

**Issue by lewtoff** [Telos-Foundation/Sqrl#51]
After attempting to transfer out of the Graviex exchange into my Sqrl account, I receive an error message due to an incorrect withdrawal address. Where will I find the correct withdrawal address in Sqrl? 

Thanks in advance

**Comment by marlonwilliams** [comment]
Sqrl uses your EOS genesis account or newly created account. You must know which account you are attempting to transfer tokens to!

**Comment by lewtoff** [comment]
Thanks Marlon,

I have confirmed my EOS genesis key on both my Sqrl wallet and a separate wallet (Exodus) however I seem to be having the same issue. Any suggestions?
