### ISSUE TITLE
Account faucet false positive on first creation

### ISSUE THREAD

**Issue by robrigo** [Telos-Foundation/Sqrl#52]
Hello, I tried to test the free account creation feature and got the following error which I assume is a false positive as I have only used a genesis account before.

<img width="352" alt="screen shot 2018-12-25 at 8 55 19 pm" src="https://user-images.githubusercontent.com/590263/50428675-89fa4c00-0887-11e9-9658-4b9dd652e034.png">

I backed up and wiped my app data so that the wallet would reset to the flow that happens the first time you access it in order to reproduce.

**Comment by marlonwilliams** [comment]
Discussed this with @robrigo in Telegram. Thanks for the chat and clarification, Rob!
