### ISSUE TITLE
Can't login in to Dapp when using tether network

### ISSUE THREAD

**Issue by MaxResolution** [Telos-Foundation/Sqrl#55]
Equipment: MacBook Pro 2018, iPhone 8 Plus running iOS12

Sqrl can't not login to Dapp when MacBook using iPhone's 4g hotspot (account selection not showing up), but it works on regular wifi.

**Comment by marlonwilliams** [comment]
Unfortunately, Sqrl working on a 4g hotspot is not something we have time to troubleshoot.
