### ISSUE TITLE
The threshold of free accounts that can be created per hour has been exceeded.

### ISSUE THREAD

**Issue by matthewb2012** [Telos-Foundation/Sqrl#62]
![image](https://user-images.githubusercontent.com/6923869/51222340-f0acdb80-1902-11e9-86e1-7ccd2bec43ae.png)

**Comment by matthewb2012** [comment]
On http://telostracker.io/listaccounts/1 the last cbd account of the many that were created finished at 4:30 Pm CST. I was not involved in those accounts but the last one was there at 4:30. So there were only 4 other accounts created between 4:30 and about 8 Pm when I got this "per hour" error. Is it a problem?

**Comment by marlonwilliams** [comment]
we've made some adjustments here and this happens much less frequent
