### ISSUE TITLE
Creating a new account is unnecessary complicated

### ISSUE THREAD

**Issue by miohtama** [Telos-Foundation/Sqrl#64]
For new users it is not immediate obvious how to create a new account

You get a hint

<img width="322" alt="image" src="https://user-images.githubusercontent.com/49922/52162997-57880e00-26d3-11e9-8acf-c78eead963ff.png">

That points to 

<img width="922" alt="image" src="https://user-images.githubusercontent.com/49922/52162993-46d79800-26d3-11e9-83c7-b47741bb90a0.png">

But actual account creation is here:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/49922/52163002-71c1ec00-26d3-11e9-8121-c3ede0c08458.png">

... which does not tell how to create a key, should link to key generate

On Key generator it does not say which is public key and what is private key, instead refers them by 0 and 1

<img width="632" alt="image" src="https://user-images.githubusercontent.com/49922/52163024-cf563880-26d3-11e9-95a7-c617460abfd1.png">

I would recommend to have a 

- direct link "create a new account"

- an explanation and manage of expectations what is needed for a new account and how user can fill these expectations (cost, how much time it takes to set up, etc.)

- on create account page offer an option to generate keys inline

- have a link to a tutorial and some policy what account creation costs and who pays for it

- Have the create account page to prepolulate RAM bytes etc. with default values and hide them behind Advanced tab

I feel this is a pain point for new users like myself, so good to discuss this to make Telos adoption easier.

**Comment by marlonwilliams** [comment]
Good day,

Changing the way account creation works is not on our radar at this time, but we appreciate the feedback.
