### ISSUE TITLE
Registered arbitrators do not see a button to unregister themselves

### ISSUE THREAD

**Issue by DouglasHorn** [Telos-Foundation/Sqrl#70]
Sqrl 1.0.3

I have heard a report from an arbitrator that the unregister button does not appear for them. This was within the period before voting. I was able to guide this person through the process using the smart contract interface, so I know it was possible.

My guess is that this may stem from changing the unregister action name from unregcand to unregnominee.

**Comment by marlonwilliams** [comment]
Confirmed. Will be fixed in next update

**Comment by marlonwilliams** [comment]
We've updated this in the current release, but the current election has already begun. Thanks for identifying.
