### ISSUE TITLE
Voting for one arbitrator triggers response that all arbs have been voted for and they become unvotable

### ISSUE THREAD

**Issue by DouglasHorn** [Telos-Foundation/Sqrl#71]
Sqrl 1.0.3 
When an account votes for one arbitrator, the interface shows "You voted for this candidate" for every candidate, not just the one voted for. Subsequently, the checkmark button for the other arbitrators become unvoteable. 

I have determined that this is NOT caused because Sqrl is actually voting for multiple arbitrators with the initial voting action. Moreover, it is still possible to vote for additional arbitrator candidates using the smart contract interface with eosio.trail::castvote.

It appears that there is simply a problem with the interface. However, it prevents most users from voting for multiple arbitrator candidates.

**Comment by marlonwilliams** [comment]
This has been resolved in the latest Sqrl 1.0.4 patch release. Thanks for reporting.
