### ISSUE TITLE
Proposals submission page reports incorrect fee amount

### ISSUE THREAD

**Issue by DouglasHorn** [Telos-Foundation/Sqrl#75]
When submitting a worker proposal, the screen warns users that there will be a 50.0000 TLOS fee. There are two problems with this.

First, the actual fee is 3% of the requested amount of the WP with a minimum of 50.0000 TLOS.

Second, this deposit needs to be paid from the sending account to eosio.saving BEFORE the WP is submitted, or else the submission will fail with an Error 500.

Recommendation: Update the fee calculation to be 3% of the requested amount (50.0000 TLOS minimum) and change the text to indicate "You must submit a deposit of 3% of the requested proposal amount (minimum 50 TLOS) {deposit amount} from this account to `eosio.saving` _before_ submitting this proposal or the submission will fail. If you have not made this submission, please first transfer this amount of tokens to eosio.saving before submitting this proposal."

**Comment by marlonwilliams** [comment]
Thanks. Resolved in v1.0.5
