### ISSUE TITLE
WP Proposal is showing wrong number of cycles

### ISSUE THREAD

**Issue by DouglasHorn** [Telos-Foundation/Sqrl#79]
Sqrl 1.0.5 
The Governance | Proposals tab is incorrectly displaying the number of cycles. It is showing:

`Amount Requested: {amount} in {cycles} cycle(s)` 

but should actually show:

`Amount Requested: {amount} in {cycles-1} cycle(s)`

Because `cycles` is actually written as `n+1` where `n` is the number of cycles the WP will have. The +1 is to accommodate the period before `openvoting` is called.

Note that all entries have n+1 cycles
![screen shot 2019-03-06 at 2 21 39 pm](https://user-images.githubusercontent.com/37677685/53918814-e4005600-401c-11e9-9da5-8f2b44096369.png)

This appears to be a change that occurred during the update to 1.0.5 because 1.0.4 shows this correctly:

![screen shot 2019-03-06 at 2 15 43 pm](https://user-images.githubusercontent.com/37677685/53918955-5a04bd00-401d-11e9-8be8-72e50e42d8c4.png)

**Comment by marlonwilliams** [comment]
Was already resolved. Will be visible in next release which includes another big feature addition as well. Closing.
