### ISSUE TITLE
Request for access to language files for transalation to Russian

### ISSUE THREAD

**Issue by roger-eosuk** [Telos-Foundation/Sqrl#85]
We (the Telos community) have received an offer to translate Sqrl texts into Russian by Telegram user @dicrypt1d so I have offered to help connect the user with Sqrl team so see if we can get them access to the text strings for translation.
Please advise the best way to proceed.
Cheers
Rog

**Comment by roger-eosuk** [comment]
I think the files have been provided by Marlon already so it is with @dicrypt1d

**Comment by marlonwilliams** [comment]
Thanks 👍
